services:
  # 1. API Gateway Entry Point
  - type: web
    name: saep-gateway
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SERVICE_NAME
        value: saep-gateway
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: saep-postgres
          property: connectionString

  # 2. Core Identity Microservice
  - type: web
    name: saep-identity
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SERVICE_NAME
        value: saep-identity
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: saep-postgres
          property: connectionString

  # 3. Company & Hierarchy Microservice
  - type: web
    name: saep-company
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SERVICE_NAME
        value: saep-company
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: saep-postgres
          property: connectionString

databases:
  - name: saep-postgres
    databaseName: saep_db
    user: saep_user
    plan: free
