server:
  port: 8085

spring:
  application:
    name: saep-marketplace
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/saep_marketplace
    username: saep_user
    password: saep_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:z+y9w1XfR/qj5H+c8V2P4mK7s9tL6bN3yQ1w8Z4c5vA=}
