server:
  port: 8086

spring:
  application:
    name: saep-governance
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/saep_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redispassword}

temporal:
  address: ${TEMPORAL_ADDRESS:127.0.0.1:7233}
  namespace: default
  task-queue: GOVERNANCE_TASK_QUEUE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
