spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.main.allow-bean-definition-overriding=true
spring.datasource.hikari.schema=saep_memory
spring.jpa.properties.hibernate.default_schema=saep_memory
spring.flyway.schemas=saep_memory
spring.flyway.default-schema=saep_memory
spring.flyway.create-schemas=true
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration,com.saep.common.security.SaepSecurityConfig
spring.datasource.username=postgres
spring.datasource.password=password
