server:
  port: 8082

spring:
  application:
    name: saep-workforce
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/saep_workforce
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: saep-workforce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redispassword}

saep:
  outbox:
    poll-interval-ms: 5000
    enabled: false
  test:
    force-failure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
