server:
  port: 8087

spring:
  application:
    name: saep-workflow

temporal:
  connection:
    target: "127.0.0.1:7233"
  workersAutoDiscovery:
    autoStart: true
  workers:
    - taskQueue: "SAEP_TASK_QUEUE"
      capacity:
        maxConcurrentWorkflowTaskExecutionSize: 10
        maxConcurrentActivityExecutionSize: 10

saep:
  security:
    jwt:
      secret: "saep-super-secret-key-for-development-only-must-be-changed-in-production"
